placeholder:
  dir_out_global: None
  dir_out_single: None
  dir_out_name: None
  multi_ws: None
  file_num: None
  tol_rt: None
  locus_rt_thre: None
  gpu_id: None
  is_overwrite: False
  ws_single: None

identification:
  fg_num: 12 # maximum number of fragment ions per target peptide

  sample_ratio: 0.1 # estimate the tol by sampling from lib
  rubbish_q_cut: 0.5 # q threshold from DIA-NN source code
  top_sa_cut: 0.75 # candidate locus must have SA > ratio of the maximum
  top_deep_cut: 0.66 # candidate locus must have Deep > ratio of the maximum

  tol_rt_ratio: 0.0667 # 1/15 of the gradient as the init tol_rt
  tol_im_xic_before_calib: 0.08 # init tol 1/k0. For centroid data.
  tol_im_xic_after_calib: 0.05 # refined tol 1/k0
  tol_im_xic: 0.08
  tol_ppm_before_calib: 20  # init tol for centroid or profile data
  tol_ppm: 20

  tol_im_map: 0.025 # half width of im for DeepMap
  map_im_gap: 0.001 # bin width in im dimension for DeepMap
  map_im_dim: 50 # int(2 * tol_im_map / map_im_gap)
  map_cycle_dim: 13 # locus with 13 cycles
  patient: 5 # epoch stop for deepmap retrain or deepmall train

  window_points: 7 # SA only using 7 cycles.
  q_cut_infer: None # which prs will be used for protein group infer and score

quantification:
  top_k_fg: 5 # select top_k_fg ions for cross quantification of precursors
  top_k_pr: 1 # select top_k_pr prs for protein quantification

efficiency:
  target_batch_max: 450000 # batch size for analysis

chemical:
  mass_proton: 1
  mass_aa:
    A: 89.0476792233
    C: 160.030644505
    D: 133.0375092233
    E: 147.05315928710002
    F: 165.07897935090006
    G: 75.0320291595
    H: 155.06947728710003
    I: 131.0946294147
    K: 146.10552844660003
    L: 131.0946294147
    M: 149.05105008089998
    m: 165.04596508089998
    N: 132.0534932552
    P: 115.06332928709999
    Q: 146.06914331900003
    R: 174.11167644660003
    S: 105.0425942233
    T: 119.05824428710001
    V: 117.0789793509
    W: 204.0898783828
    Y: 181.07389435090005
    c: 178.04121404900002

develop_use:
  is_compare_mode: False
  locus_valid_num: 3.5 # locuses from Full-DIA and DIA-NN within this value are considered consistent
